name: Update M3U to Branch m3u

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  deploy-playlist:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Checkout repository hiện tại (playlist) để lấy môi trường
      - name: Checkout Playlist Repo
        uses: actions/checkout@v3
        with:
          path: main_repo

      # 2. Checkout repository chứa code Python (backup)
      # Nếu repo 'backup' là Private, GitHub sẽ dùng ENGINE_TOKEN để tải
      - name: Checkout Backup Repo
        uses: actions/checkout@v3
        with:
          repository: zaltvvn/backup
          token: ${{ secrets.ENGINE_TOKEN }}
          path: backup

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      # 3. Chạy Script (Lúc này file nằm trong thư mục python_scripts)
      - name: Run Script
        run: python backup/get-playlist-ae.py
        
      # 4. Đẩy file playlist_updated.m3u sang nhánh m3u
      - name: Deploy to m3u Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ENGINE_TOKEN }}
          publish_branch: m3u
          publish_dir: ./
          keep_files: false
          commit_message: "Auto update live channels $(date)"
          # Loại bỏ các thư mục repo vừa tải về để tránh đẩy ngược lên nhánh m3u
          exclude_assets: "python_scripts/**,main_repo/**,.*,*.yml"
