name: Update All M3U Playlists

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  deploy-playlists:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Playlist Repo
        uses: actions/checkout@v3

      - name: Checkout Backup Repo
        uses: actions/checkout@v3
        with:
          repository: zaltvvn/backup
          token: ${{ secrets.ENGINE_TOKEN }}
          path: backup

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      # Chạy lần lượt cả 2 Script
      - name: Run Scripts
        run: |
          python backup/get-playlist-ae.py
          python backup/get-playlist-in.py

      # Gom cả 2 file vào chung 1 thư mục
      - name: Prepare Output Folder
        run: |
          mkdir -p final_output
          
          if [ -f "playlist_ae.m3u" ]; then
            mv playlist_ae.m3u final_output/
            echo "✅ Gom file AE thành công!"
          else
            echo "⚠️ Không tìm thấy file AE!"
          fi
          
          if [ -f "playlist_in.m3u" ]; then
            mv playlist_in.m3u final_output/
            echo "✅ Gom file IN thành công!"
          else
            echo "⚠️ Không tìm thấy file IN!"
          fi

      # -----------------------------------------------------------
      # BƯỚC MỚI: Tính toán ngày giờ VN và lưu vào biến GITHUB_ENV
      # -----------------------------------------------------------
      - name: Get Current Time
        run: echo "TIME_NOW=$(TZ='Asia/Ho_Chi_Minh' date +'%d/%m %H:%M')" >> $GITHUB_ENV

      # -----------------------------------------------------------
      # BƯỚC DEPLOY: Gọi biến thời gian ra bằng ${{ env.TIME_NOW }}
      # -----------------------------------------------------------
      - name: Deploy to m3u Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ENGINE_TOKEN }}
          publish_branch: m3u
          publish_dir: ./final_output
          keep_files: false 
          force_orphan: true
          commit_message: "Auto Update: All Playlists - Cập nhật lúc ${{ env.TIME_NOW }}"
