name: Update M3U to Branch m3u

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  deploy-playlist:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Checkout repo 'playlist' (công khai) vào thư mục gốc
      - name: Checkout Playlist Repo
        uses: actions/checkout@v3

      # 2. Checkout repo 'backup' (Private) vào thư mục 'backup'
      - name: Checkout Backup Repo
        uses: actions/checkout@v3
        with:
          repository: zaltvvn/backup
          token: ${{ secrets.ENGINE_TOKEN }}
          path: backup

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      # 3. Chạy Script (Script này sẽ tạo ra thư mục 'output/playlist_ae.m3u')
      - name: Run Script
        run: python backup/get-playlist-ae.py

      # 4. Bước KIỂM TRA (Để bạn xem trong Log có file chưa)
      - name: Check output file
        run: ls -R output/

      # 5. Đẩy DUY NHẤT thư mục 'output' lên nhánh m3u
      - name: Deploy to m3u Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ENGINE_TOKEN }}
          publish_branch: m3u
          publish_dir: ./output  # <--- Chỉ đẩy nội dung trong thư mục output
          keep_files: false
          commit_message: "Auto update playlist: playlist_ae.m3u $(date)"
